export const FETCH_PERSON_REQ = 'FETCH_PERSON';
export const FETCH_FACILITY_REQ = 'FETCH_FACILITY';
export const FETCH_EXPOSURE_REQ = 'FETCH_EXPOSURE';

export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
export const FETCH_FACILITY_SUCCESS = 'FETCH_FACILITY_SUCCESS';
export const FETCH_EXPOSURE_SUCCESS = 'FETCH_EXPOSURE_SUCCESS';

export const FETCH_PERSON_FAIL = 'FETCH_PERSON_FAIL';
export const FETCH_FACILITY_FAIL = 'FETCH_FACILITY_FAIL';
export const FETCH_EXPOSURE_FAIL = 'FETCH_EXPOSURE_FAIL';

export const FETCH_ERROR = 'FETCH_ERROR';